"""Locks the exact versions and hashes of the build packages: requirements.lock and requirements-pip.lock.

The versions come from the development environment .venv — the versions that passed the checks.
SHA-256 hashes come from PyPI: every wheel file of each version. Before writing, the versions are checked
against the OSV database (vulnerabilities and malicious packages): if anything is found, nothing is written.

Run: .venv\\Scripts\\python tools\\make_lock.py
Update the lock files only deliberately: after updating the packages in .venv and checking them.
"""
from __future__ import annotations

import json
import sys
import urllib.request
from importlib import metadata
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parent.parent
ROOTS = ["web3", "PySide6-Essentials", "pyinstaller"]  # the program and the .exe builder


def get_json(url: str, payload: dict | None = None) -> dict:
    body = json.dumps(payload).encode() if payload is not None else None
    request = urllib.request.Request(url, data=body, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return json.loads(response.read())


def closure(roots: list[str]) -> dict[str, metadata.Distribution]:
    """Every package the root ones need, with platform markers and extras (eth-hash[pycryptodome])."""
    environment = default_environment()
    found: dict[str, tuple[metadata.Distribution, set[str]]] = {}
    stack = [Requirement(name) for name in roots]
    while stack:
        requirement = stack.pop()
        name = canonicalize_name(requirement.name)
        dist, extras = found.get(name, (metadata.distribution(requirement.name), set()))
        new_extras = set(requirement.extras) - extras
        if name in found and not new_extras:
            continue
        extras |= new_extras
        found[name] = (dist, extras)
        for line in dist.requires or []:
            dependency = Requirement(line)
            if dependency.marker is not None and not any(
                    dependency.marker.evaluate({**environment, "extra": extra}) for extra in extras | {""}):
                continue
            stack.append(dependency)
    return {name: dist for name, (dist, _) in found.items()}


def wheel_hashes(name: str, version: str) -> list[str]:
    release = get_json(f"https://pypi.org/pypi/{name}/{version}/json")
    if release["info"].get("yanked"):
        raise SystemExit(f"{name}=={version} was yanked from PyPI by its author")
    hashes = sorted(item["digests"]["sha256"] for item in release["urls"] if item["packagetype"] == "bdist_wheel")
    if not hashes:
        raise SystemExit(f"{name}=={version} has no ready-made wheels — building from sources is not allowed")
    return hashes


def lock_lines(packages: dict[str, str]) -> list[str]:
    lines = []
    for name, version in sorted(packages.items()):
        hashes = wheel_hashes(name, version)
        lines.append(f"{name}=={version} \\")
        lines.extend(f"    --hash=sha256:{digest}" + (" \\" if i < len(hashes) - 1 else "")
                     for i, digest in enumerate(hashes))
    return lines


def main() -> int:
    packages = {name: dist.version for name, dist in closure(ROOTS).items()}
    pip_version = metadata.version("pip")
    queries = [{"package": {"name": name, "ecosystem": "PyPI"}, "version": version}
               for name, version in {**packages, "pip": pip_version}.items()]
    results = get_json("https://api.osv.dev/v1/querybatch", {"queries": queries})["results"]
    problems = [(q["package"]["name"], q["version"], [v["id"] for v in r.get("vulns") or []])
                for q, r in zip(queries, results) if r.get("vulns")]
    if problems:
        for name, version, ids in problems:
            print(f"OSV: {name}=={version}: {ids}")
        print("There are vulnerable or malicious versions — the lock files were not written.")
        return 1
    # pip reads these files in the Windows code page, so they are ASCII only
    header = ["# Exact versions and SHA-256 hashes of every package used to build ETH_Sender.exe.",
              "# Generated by tools/make_lock.py from the verified .venv; do not edit by hand.",
              "# Install: pip install --require-hashes --only-binary=:all: -r requirements.lock", ""]
    (ROOT / "requirements.lock").write_text("\n".join(header + lock_lines(packages)) + "\n", encoding="ascii")
    (ROOT / "requirements-pip.lock").write_text(
        "\n".join(["# pip itself for the clean build environment; generated by tools/make_lock.py", ""]
                  + lock_lines({"pip": pip_version})) + "\n", encoding="ascii")
    print(f"requirements.lock: {len(packages)} packages; requirements-pip.lock: pip {pip_version}; OSV: clean")
    return 0


if __name__ == "__main__":
    sys.exit(main())
